blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/eon-fun/pantheon-agent-template/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/eon-fun/pantheon-agent-template/blob/main/docs/CONTRIBUTING.md
    about: Check our contributing guide for development workflows.
